## NUMERO IDDL APPROVATI NELLA 17esima LEGISLATURA #

PREFIX osr: <http://dati.senato.it/osr/>


SELECT  ?idddl, ?titolo, str(?dataPresentazione) AS ?dataPresentazione, ?dataApprovazione
{
?ddl osr:dataStatoDdl ?dataApprovazione .
?ddl osr:dataStatoDdl ?dataApprovazione .
?ddl osr:idDdl ?idddl .
?ddl osr:titolo ?titolo .
?ddl osr:statoDdl ?stato .
?ddl osr:legislatura 16 .
?ddl osr:dataPresentazione ?dataPresentazione .
?ddl osr:ramo ?ramo

{ SELECT ?idddl (MAX(?dataStato2) AS ?maxDataStato)
     WHERE
     {  
?ddl2 osr:dataStatoDdl ?dataStato2 .
?ddl2 osr:idDdl ?idddl
} 
}

FILTER (?dataStato = ?maxDataStato).

FILTER (REGEX(?stato,'approvato definitivamente','i')).

}
