# NUMERO IDDL APPROVATI NELLA 17esima LEGISLATURA #

PREFIX osr: <http://dati.senato.it/osr/>

SELECT ?ddl, ?idddl, ?titolo, str(?dataPresentazione) AS ?dataPresentazione, ?dataApprovazione {
	?ddl osr:idDdl ?idddl . 
	?ddl osr:titolo ?titolo .
	?ddl osr:statoDdl ?stato .
	?ddl osr:legislatura 17 . # selezione sulla 17esima legislatura
	?ddl osr:dataPresentazione ?dataPresentazione .
	?ddl osr:ramo ?ramo { 
		SELECT ?idddl, (MAX(?dataStato2) AS ?dataApprovazione) { # la massima dataStato e' considerata come quella di approvazione
			?ddl2 osr:dataStatoDdl ?dataStato2 .
			?ddl2 osr:idDdl ?idddl
		} 
	}
 
	FILTER (REGEX(?stato,'approvato definitivamente','i')) . # filtro con regex sul tipo di stato
}